stages:
- push

docker_push:
    stage: push
    image:
        name: gcr.io/go-containerregistry/crane:debug
        entrypoint: [""]
    script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY