stages:
- test
    

run_tests:
    stage: test
    only:
    - 6-add-tests-to-wsi-service
    image:
        name: python
        entrypoint: [""]
    tags:
    - asprunner
    script:
    - python --version
