stages:
- test
- build_and_test
- build_and_push

run_tests:
    stage: test
    image:
        name: python
    tags:
    - asprunner
    script:
    - apt-get update && apt-get install -y python3-openslide
    - pip3 install -e .
    - pytest

build_and_test_docker_image:
    stage: build_and_test
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    tags:
    - asprunner    
    script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile_test --destination $CI_REGISTRY_IMAGE:test --no-push

build_and_push_docker_image:
    stage: build_and_push
    only:
    - 6-add-tests-to-wsi-service
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    tags:
    - asprunner    
    script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - export BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:test --label org.opencontainers.image.created=$BUILD_TIME --label org.opencontainers.image.authors="Fraunhofer MEVIS" --label org.opencontainers.image.vendor="Fraunhofer MEVIS" --label org.opencontainers.image.version=$CI_COMMIT_TAG --label org.opencontainers.image.source=$CI_PROJECT_URL --label org.opencontainers.image.revision=$CI_COMMIT_SHA --label org.opencontainers.image.title="WSI-Service" --label org.opencontainers.image.description="WSI-Service to stream whole slide images tile-based via HTTP"
