stages:
- test
    

run_tests:
    stage: test
    only:
    - 6-add-tests-to-wsi-service
    image:
        name: python:3.7
        entrypoint: [""]
    tags:
    - asprunner
    script:
    - apt-get install -y python3-openslide
    - pip3 install -e .
