stages:
- build
    
build_docker_image:
    stage: build
    only:
    - master
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    tags:
    - asprunner    
    script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE --label org.opencontainers.image.created=$CI_JOB_TIMESTAMP --label org.opencontainers.image.authors="Fraunhofer MEVIS" --org.opencontainers.image.version=CI_COMMIT_TAG --label org.opencontainers.image.source=$CI_REPOSITORY_URL --label org.opencontainers.image.revision=$CI_COMMIT_SHA --label org.opencontainers.image.title="WSI-Service" --label org.opencontainers.image.description="WSI-Service to stream whole slide images tile-based via HTTP"
