include:
  - project: "empaia/integration/ci-templates"
    ref: "main"
    file:
      - "pipeline-templates/pipeline-poetry-standard.yml"
      - "job-templates/docker-init.yml"
      - "job-templates/poetry-codecheck.yml"

variables:
  TITLE: "WSIS"
  DESCRIPTION: "Whole Slide Image Service (WSIS)"
  DIRECTORY: "wsi_service"
  TEST_DIRECTORY: "wsi_service/tests"
  RUNNER_TAG: "empaia-parallel"
  RUNNER_DOCKER_TAG: "empaia-docker"
  HOST_PORT: 8080
  CONTAINER_PORT: 8080
  DOCKER_RUN_ALIVE_TEST: "true"

poetry-codecheck-plugins:
  extends: .poetry-codecheck
  variables:
    DIRECTORY: "wsi_service_base_plugins"

docker-based-pytest:
  extends: .docker-init
  tags:
    - empaia-docker
    - testdata
  before_script:
    - !reference [.docker-init, before_script]
    - cp wsi_service/tests/integration/env_tests .env
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --build -d
    - sleep 10
  script:
    - docker exec wsi-service_wsi_service_1 poetry run pytest --cov wsi_service
  after_script:
    - docker exec wsi-service_wsi_service_1 rm -r .pytest_cache
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
    - !reference [.docker-init, after_script]

docker-build-and-push:
  needs:
    - !reference [.docker-build-and-push-default-needs, needs]
    - job: docker-based-pytest
    - job: poetry-codecheck-plugins
