stages:
- static_analysis
- test
- build_docker

run_static_analysis:
    stage: static_analysis
    image:
        name: python
    tags:
    - wsi-service-runner
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
    - ls /data
    - pip3 install black isort pylint
    - black . --check
    - isort . --check --profile black
    - pylint wsi_service --disable=all --enable=F,E,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode --extension-pkg-whitelist=pydantic --disable=F0401

run_test:
    stage: test
    image:
        name: python
    tags:
    - wsi-service-runner
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
    - apt-get update && apt-get install -y python3-openslide
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry install
    - poetry run pytest --cov=wsi_service wsi_service/tests/

run_build_docker:
    stage: build_docker
    only:
    - master
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    tags:
    - asprunner    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - export BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE --label org.opencontainers.image.created=$BUILD_TIME --label org.opencontainers.image.authors="Fraunhofer MEVIS" --label org.opencontainers.image.vendor="Fraunhofer MEVIS" --label org.opencontainers.image.version=$CI_COMMIT_TAG --label org.opencontainers.image.source=$CI_PROJECT_URL --label org.opencontainers.image.revision=$CI_COMMIT_SHA --label org.opencontainers.image.title="WSI Service" --label org.opencontainers.image.description="WSI-Service to stream whole slide images tile-based via HTTP"
