version: "3.8"

services:
  wsi_service:
    build:
      target: wsi_service_dev
    command:
      [
        "sh",
        "-c",
        "poetry run python -m uvicorn wsi_service.api:api --host 0.0.0.0 --loop=uvloop --http=httptools --port 8080"
      ]
    ports:
      - 5678:5678
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS=5
      - WS_IMAGE_HANDLE_CACHE_SIZE=6
      - NO_PROXY=localhost,127.0.0.1,testserver
