version: "3.8"

services:
  wsi_service:
    image: registry.gitlab.com/empaia/services/wsi-service
    build:
      context: "."
      network: "${COMPOSE_NETWORK}"
    restart: "${COMPOSE_RESTART}"
    environment:
      - WS_CORS_ALLOW_CREDENTIALS=${WS_CORS_ALLOW_CREDENTIALS}
      - WS_CORS_ALLOW_ORIGINS=${WS_CORS_ALLOW_ORIGINS}
      - WS_DEBUG=${WS_DEBUG}
      - WS_DISABLE_OPENAPI=${WS_DISABLE_OPENAPI}
      - WS_MAPPER_ADDRESS=http://storage-mapper-service:8000/v3/slides/{slide_id}
      - WS_LOCAL_MODE=False
      - WS_ENABLE_VIEWER_ROUTES=${WS_ENABLE_VIEWER_ROUTES}
      - WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS=${WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS}
      - WS_MAX_RETURNED_REGION_SIZE=${WS_MAX_RETURNED_REGION_SIZE}
    volumes:
      - ${COMPOSE_DATA_DIR}:/data
    ports:
      - ${COMPOSE_WS_PORT}:8080

  storage-mapper-service:
    image: registry.gitlab.com/empaia/services/storage-mapper-service:0.2.10@sha256:105b6ab0a58a0079961aeb5f65b89fc63b17aacb3f5bdbf8ddcda4abc857320e
    environment:
      SM_DB_USERNAME: empaia_test
      SM_DB_PASSWORD: A6tP3osxByeM
      SM_DB: storage-mapper
      SM_DB_HOST: storage-mapper-service-db
      SM_DB_PORT: 5432
    ports:
      - 8081:8000
    depends_on:
      - storage-mapper-service-db

  storage-mapper-service-db:
    image: registry.gitlab.com/empaia/integration/custom-pg:14
    restart: ${COMPOSE_RESTART}
    command: postgres -c config_file=/etc/postgresql/postgres.conf
    environment:
      POSTGRES_DB: storage-mapper
      POSTGRES_USER: empaia_test
      POSTGRES_PASSWORD: A6tP3osxByeM
