version: "3.8"

services:
  isyntax-backend:
    build:
      context: "./wsi_service/loader_plugins/isyntax"
      network: ${COMPOSE_NETWORK}
      args:
        - ISX_PHILIPS_SDK_FILEPATH=${ISX_PHILIPS_SDK_FILEPATH}
    restart: ${COMPOSE_RESTART}
    environment:
      PYTHONUNBUFFERED: 1
      WS_ISYNTAX_PORT: ${WS_ISYNTAX_PORT}
    tty: true
    volumes:
      - ./wsi_service/loader_plugins/isyntax:/root/isyntax/backend
      - ${WS_DATA_DIR}:/data
    command: python3 -m backend.__main__
    ports:
      - ${WS_ISYNTAX_PORT}:5556

  wsi_service:
    build:
      context: "."
      network: ${COMPOSE_NETWORK}
    command:
      - uvicorn
      - --host=0.0.0.0
      - --port=8080
      - --reload
      - wsi_service.api:api
    restart: ${COMPOSE_RESTART}
    environment:
      WS_CORS_ALLOW_ORIGINS: ${WS_CORS_ALLOW_ORIGINS}
      WS_DISABLE_OPENAPI: ${WS_DISABLE_OPENAPI}
      WS_PORT: ${WS_PORT}
      WS_ISYNTAX_PORT: ${WS_ISYNTAX_PORT}
      WS_DEBUG: ${WS_DEBUG}
      WS_DATA_DIR: "/data"
      WS_MAPPER_ADDRESS: ${WS_MAPPER_ADDRESS}
      WS_LOCAL_MODE: ${WS_LOCAL_MODE}
      WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS: ${WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS}
      WS_MAX_RETURNED_REGION_SIZE: ${WS_MAX_RETURNED_REGION_SIZE}
      WS_ROOT_PATH: ${WS_ROOT_PATH}
    tty: true
    volumes:
      - ./wsi_service/:/usr/local/lib/python3.9/site-packages/wsi_service/
      - ${WS_DATA_DIR}:/data
    ports:
      - ${WS_PORT}:8080
