version: "3.8"

services:
  isyntax-backend:
    build:
      context: "./wsi_service/loader_plugins/isyntax"
      network: ${COMPOSE_NETWORK}
    restart: ${COMPOSE_RESTART}
    environment:
      PYTHONUNBUFFERED: 1
      WS_ISYNTAX_PORT: 5556
    volumes:
      - ${COMPOSE_DATA_DIR}:/data
    ports:
      - ${COMPOSE_ISYNTAX_PORT}:5556

  wsi_service:
    build:
      context: "."
      network: ${COMPOSE_NETWORK}
    command:
      - uvicorn
      - --host=0.0.0.0
      - --port=8080
      - --reload
      - wsi_service.api:api
    restart: ${COMPOSE_RESTART}
    environment:
      WS_CORS_ALLOW_ORIGINS: ${WS_CORS_ALLOW_ORIGINS}
      WS_DISABLE_OPENAPI: ${WS_DISABLE_OPENAPI}
      WS_ISYNTAX_PORT: 5556
      WS_DEBUG: ${WS_DEBUG}
      WS_DATA_DIR: /data
      WS_MAPPER_ADDRESS: ${WS_MAPPER_ADDRESS}
      WS_LOCAL_MODE: ${WS_LOCAL_MODE}
      WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS: ${WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS}
      WS_MAX_RETURNED_REGION_SIZE: ${WS_MAX_RETURNED_REGION_SIZE}
      WS_ROOT_PATH: ${WS_ROOT_PATH}
    volumes:
      - ${COMPOSE_DATA_DIR}:/data
    ports:
      - ${COMPOSE_WS_PORT}:8080
