[tool.poetry]
name = "wsi-service"
version = "0.4.3"
description = "EMPAIA WSI Service to stream whole slide images"
authors = ["EMPAIA <dev-support@empaia.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
fastapi = "^0.65.2"
starlette = "^0.14.2"
requests = "^2.25.0"
uvicorn = "^0.12.3"
numpy = "^1.21.0"
Pillow = "^8.0.1"
imagecodecs = "^2021.1.11"
tifffile = "^2021.1.14"

[tool.poetry.dev-dependencies]
black = "^21.5b2"
debugpy = "^1.3.0"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest-cov = "^2.10.1"
pytest = "^6.1.2"
requests-mock = "^1.8.0"
requests = "^2.7.0"
wsi-service-plugin-tifffile = { path = "wsi_service_base_plugins/tifffile", develop = true }
wsi-service-plugin-openslide = { path = "wsi_service_base_plugins/openslide", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
include_trailing_comma = true
