[tool.poetry]
name = "wsi_service"
version = "0.2.4"
description = "The WSI Service enables users to stream Whole Slide Images (WSI) tile-based via HTTP. It is based on a FastAPI webserver and OpenSlide to access whole slide image data."
authors = ["Michael Franz", "Henning Höfener", "Johannes Lotz", "Nick Weiss",]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.0.1"
fastapi = "^0.61.2"
requests = "^2.25.0"
uvicorn = "^0.12.3"
zipfile36 = "^0.1.3"
openslide-wrapper = "^1.1.2"
tifffile = "^2021.1.14"
imagecodecs = "^2021.1.11"
scikit-image ="^0.18.1"
pyzmq = "^22.0.3"
cffi = "^1.14.5"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest-cov = "^2.10.1"
pytest = "^6.1.2"
requests-mock = "^1.8.0"
requests = "^2.7.0"
docker-compose = "^1.29.0"
pytest-docker = "^0.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
exclude = 'wsi_service/models'

[tool.isort]
profile = "black"
skip = 'wsi_service/models'
