[tool.poetry]
name = "wsi_service"
version = "0.1.0"
description = "The WSI Service enables users to stream Whole Slide Images (WSI) tile-based via HTTP. It is based on a FastAPI webserver and OpenSlide to access whole slide image data."
authors = ["Henning Höfener", "Johannes Lotz", "Nick Weiss"]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^8.0.1"
fastapi = "^0.61.2"
requests = "^2.25.0"
uvicorn = "^0.12.3"
zipfile36 = "^0.1.3"
openslide-wrapper = "^1.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest-cov = "^2.10.1"
pytest = "^6.1.2"
requests-mock = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
